name: baby_repository
description: Dart package which manages the baby.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  equatable: ^2.0.5
  firebase_core: ^2.24.2
  flutter:
    sdk: flutter
  meta: ^1.10.0
  intl: ^0.19.0
  rxdart: ^0.27.7
  shared_preferences: ^2.2.2
  cloud_firestore: ^4.13.6
  drift: ^2.14.0
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.0.0
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.2
  plugin_platform_interface: ^2.1.7
  drift_dev: ^2.14.0
  build_runner: ^2.4.7
