name: baby_repository
description: Dart package which manages the baby.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  equatable: ^2.0.5
  firebase_core: ^2.24.2
  flutter:
    sdk: flutter
  meta: ^1.10.0
  intl: ^0.19.0
  rxdart: ^0.27.7
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.2
  plugin_platform_interface: ^2.1.7
