// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQMnwlzO8A_aI30_LPMRVfj5PaxxJjL7k',
    appId: '1:1026106768807:web:13679e3494a8aaba914a82',
    messagingSenderId: '1026106768807',
    projectId: 'mombadycare',
    authDomain: 'mombadycare.firebaseapp.com',
    storageBucket: 'mombadycare.appspot.com',
    measurementId: 'G-LH1EC84WD5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDde2wX8mcx9Xb2R_vOMBMxnwsgcA1jRA',
    appId: '1:1026106768807:android:03eaaa19567c9d48914a82',
    messagingSenderId: '1026106768807',
    projectId: 'mombadycare',
    storageBucket: 'mombadycare.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACNAvdAHxwv6HQtfY3Y_MZie8i2Vozo3Q',
    appId: '1:1026106768807:ios:60ca2277ba5931ce914a82',
    messagingSenderId: '1026106768807',
    projectId: 'mombadycare',
    storageBucket: 'mombadycare.appspot.com',
    iosBundleId: 'com.bakarot.mombabycare.momBabyCare',
  );
}
